apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.name }}-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.env.POSTGRES_PASSWORD }}
        volumeMounts:
        - name: {{ .Values.name }}-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
