apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.name }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend={{ .Values.image.repository }}
    argocd-image-updater.argoproj.io/frontend.update-strategy: {{ .Values.argocdImageUpdater.updateStrategy }}
    argocd-image-updater.argoproj.io/frontend.pull-secret: {{ .Values.argocdImageUpdater.pullSecret }}
    argocd-image-updater.argoproj.io/frontend.force-update: {{ .Values.argocdImageUpdater.forceUpdate }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Values.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: aws-ecr-secret
      containers:
      - name:  {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
