apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: "frontend={{ .Values.image.repository }}"
    argocd-image-updater.argoproj.io/frontend.update-strategy: "digest"
    argocd-image-updater.argoproj.io/frontend.allow-tags: "regexp:^[0-9a-f]{40}$"
    argocd-image-updater.argoproj.io/frontend.pull-secret: {{ .Values.argocdImageUpdater.pullSecret | quote }}
    argocd-image-updater.argoproj.io/frontend.force-update: {{ .Values.argocdImageUpdater.forceUpdate | quote }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: aws-ecr-secret
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
