name: test-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-all-in-one:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # Test Backend
      - name: Test Backend
        run: |
          cd backend
          npm ci
          npm run lint
          npm run test:unit
          npm run test:integration
          npm run build
      
      # Test Frontend
      - name: Test Frontend
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run test
          npm run build
      
      # SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=buicongthanh861_project-aws-gitops
            -Dsonar.organization=java-woof
            -Dsonar.host.url=https://sonarcloud.io/
  
  




